### ISSUE TITLE
Replace logo

### ISSUE THREAD

**Issue by dneustadt** [FriendsOfShopware/FroshNicerAdmin#3]
### Please describe the feature you would like to see implemented.

Please replace the Shopware logo with this cool logo

![cool_logo](https://user-images.githubusercontent.com/9033214/223406804-06d4a914-538b-4189-840d-16960d8d3112.svg)

**Comment by tinect** [comment]
Pull Request is greatly appreciated.

**Comment by dneustadt** [comment]
https://github.com/FriendsOfShopware/FroshNicerAdmin/pull/4
